[package]
name = "sidekiq"
version = "0.5.0"
authors = ["Laurent Arnoud <laurent@spkdev.net>"]
description = "Rust Sidekiq Client"
repository = "https://github.com/spk/rust-sidekiq.git"
homepage = "https://github.com/spk/rust-sidekiq"
keywords = ["job", "queue", "async", "sidekiq", "client"]
license = "MIT"
readme = "README.md"

[badges]
travis-ci = { repository = "spk/rust-sidekiq" }

[dependencies]
rand = "0.3.0"
redis = "0.8.0"
serde = "0.9.0"
serde_json = "0.9.0"
r2d2 = "0.7.0"
r2d2_redis = "0.6.0"
