[package]
name = "sidekiq"
version = "0.1.3"
authors = ["Laurent Arnoud <laurent@spkdev.net>"]
description = "Rust Sidekiq Client"
repository = "https://github.com/spk/rust-sidekiq.git"
homepage = "https://github.com/spk/rust-sidekiq"
keywords = ["sidekiq", "client"]
license = "MIT"
readme = "README.md"

[dependencies]
time = "0.1"
rand = "0.3"
redis = "0.5"
rustc-serialize = "0.3"
r2d2 = "0.6"
r2d2_redis = "0.2"
