[package]
name = "sidekiq"
# When updating version, also modify html_root_url in the src/lib.rs file.
version = "0.6.0"
authors = ["Laurent Arnoud <laurent@spkdev.net>"]
description = "Rust Sidekiq Client"
repository = "https://github.com/spk/rust-sidekiq.git"
homepage = "https://github.com/spk/rust-sidekiq"
keywords = ["job", "queue", "async", "sidekiq", "client"]
license = "MIT"
readme = "README.md"

[badges]
travis-ci = { repository = "spk/rust-sidekiq" }

[dependencies]
rand = "0.3"
redis = "0.8"
serde = "1.0"
serde_json = "1.0"
r2d2 = "0.7"
r2d2_redis = "0.6"
clippy = { version = "*", optional = true }

[features]
unstable = []
lint = ["clippy"]
